### ISSUE TITLE
Implement functions currently in purescript-math

### ISSUE THREAD

**Issue by JamieBallingall** [purescript/purescript-numbers#17]
See purescript/purescript-math#31.

There is a plan to eventually deprecate purescript-math, similar to how purescript-globals was deprecated. This will involve moving a lot of functions currently in purescript-math into this repo. This issue is to track that process.

**Comment by JordanMartinez** [comment]
I think this would be a breaking change...?

**Comment by JamieBallingall** [comment]
This would be a breaking change for any compiler backend other than a Javascript one. Is there a list of other backends that we would like to see supported?

Unfortunately, I think there is a sequence of breaking changes that can't easily be compacted together. Specifically,
* This issue, moving stuff from Math into Data.Number
* Updating Data.Int with the rest of the functionality in Math and changing its dependence on Math to Data.Number
* Depreciating Math

**Comment by JordanMartinez** [comment]
@JamieBallingall We're ready to make breaking changes now. Any updates on how to move this forward?
