### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by mhmdanas** [purescript/purescript-numbers#25]

**Comment by JordanMartinez** [comment]
https://github.com/purescript/purescript-numbers/blob/master/bower.json#L4 ?

**Comment by JordanMartinez** [comment]
So, the real goal here is to determine what are all the licenses of one's dependencies, correct? And the methodology you wish to use is to look up the repo's corresponding `LICENSE` file? This repo breaks that workflow because it doesn't have the `LICENSE` file, correct?

**Comment by mhmdanas** [comment]
> So, the real goal here is to determine what are all the licenses of one's dependencies, correct?

No, the goal is to collect all of the dependencies's license texts into one file for compliance purposes (much like what [this file](https://github.com/purescript/purescript/blob/master/license-generator/generate.hs) does for the PureScript compiler).

**Comment by mhmdanas** [comment]
Not to nag or anything, but could this be done soon? I need it for https://github.com/sharkdp/insect/issues/324.

**Comment by JordanMartinez** [comment]
Feel free to submit a PR :shrug:
